SYS_SOURCES_C = clock-arch.c  event.c  stimer.c  timer.c  perms.c
SYS_SOURCES_H = clock-arch.h  clock.h  event.h  stimer.h  timer.h  perms.h

SOURCES_C += $(addprefix sys/,$(SYS_SOURCES_C))
SOURCES_H += $(addprefix sys/,$(SYS_SOURCES_H))

EXTERN_LIB += -lev
