RPL_SOURCES_C =rpl.c rpl-dag.c rpl-icmp6.c rpl-timers.c rpl-of-etx.c
RPL_SOURCES_H =rpl.h rpl-private.h

SOURCES_C += $(addprefix rpl/,$(RPL_SOURCES_C))
SOURCES_H += $(addprefix rpl/,$(RPL_SOURCES_H))
